# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'magicCounter_UI.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 338)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 60, 791, 231))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.PlayerTwoCounter_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.PlayerTwoCounter_label.setAlignment(QtCore.Qt.AlignCenter)
        self.PlayerTwoCounter_label.setObjectName("PlayerTwoCounter_label")
        self.gridLayout.addWidget(self.PlayerTwoCounter_label, 1, 3, 1, 1)
        self.playerTwo_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.playerTwo_label.setAlignment(QtCore.Qt.AlignCenter)
        self.playerTwo_label.setObjectName("playerTwo_label")
        self.gridLayout.addWidget(self.playerTwo_label, 0, 3, 1, 1)
        self.playerOne_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.playerOne_label.setAlignment(QtCore.Qt.AlignCenter)
        self.playerOne_label.setObjectName("playerOne_label")
        self.gridLayout.addWidget(self.playerOne_label, 0, 1, 1, 1)
        self.TakeLife01_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.TakeLife01_pushButton.setObjectName("TakeLife01_pushButton")
        self.gridLayout.addWidget(self.TakeLife01_pushButton, 3, 1, 1, 1)
        self.playerOneCounter_label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.playerOneCounter_label.setAlignment(QtCore.Qt.AlignCenter)
        self.playerOneCounter_label.setObjectName("playerOneCounter_label")
        self.gridLayout.addWidget(self.playerOneCounter_label, 1, 1, 1, 1)
        self.AddLife01_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.AddLife01_pushButton.setObjectName("AddLife01_pushButton")
        self.gridLayout.addWidget(self.AddLife01_pushButton, 2, 1, 1, 1)
        self.AddLife02_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.AddLife02_pushButton.setObjectName("AddLife02_pushButton")
        self.gridLayout.addWidget(self.AddLife02_pushButton, 2, 3, 1, 1)
        self.TakeLife02_pushButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.TakeLife02_pushButton.setObjectName("TakeLife02_pushButton")
        self.gridLayout.addWidget(self.TakeLife02_pushButton, 3, 3, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, 10, 791, 41))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Title_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.Title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.Title_label.setObjectName("Title_label")
        self.verticalLayout.addWidget(self.Title_label)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionSettings = QtWidgets.QAction(MainWindow)
        self.actionSettings.setObjectName("actionSettings")
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionSettings)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.PlayerTwoCounter_label.setText(_translate("MainWindow", "20"))
        self.playerTwo_label.setText(_translate("MainWindow", "Player Two"))
        self.playerOne_label.setText(_translate("MainWindow", "Player One"))
        self.TakeLife01_pushButton.setText(_translate("MainWindow", "-"))
        self.playerOneCounter_label.setText(_translate("MainWindow", "20"))
        self.AddLife01_pushButton.setText(_translate("MainWindow", "+"))
        self.AddLife02_pushButton.setText(_translate("MainWindow", "+"))
        self.TakeLife02_pushButton.setText(_translate("MainWindow", "-"))
        self.Title_label.setText(_translate("MainWindow", "Magic: The Gathering LIFE COUNTER"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionSettings.setText(_translate("MainWindow", "Settings"))

